"""add auto increment to wali and kelas table

Revision ID: 5b6ea10d8b5d
Revises: 60c6bc71bfa6
Create Date: 2026-06-09 09:35:45.025918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6ea10d8b5d'
down_revision: Union[str, Sequence[str], None] = '60c6bc71bfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("siswa", "id",
        existing_type=sa.Integer(),
        autoincrement=True,
        existing_nullable=False
    )

    op.alter_column("wali", "id",
        existing_type=sa.Integer(),
        autoincrement=True,
        existing_nullable=False
    )

    op.alter_column("kelas", "id",
        existing_type=sa.Integer(),
        autoincrement=True,
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("siswa", "id",
        existing_type=sa.Integer(),
        autoincrement=False,
        existing_nullable=False
    )

    op.alter_column("wali", "id",
        existing_type=sa.Integer(),
        autoincrement=False,
        existing_nullable=False
    )

    op.alter_column("kelas", "id",
        existing_type=sa.Integer(),
        autoincrement=False,
        existing_nullable=False
    )
    # ### end Alembic commands ###
