"""Initial migration

Revision ID: 60c6bc71bfa6
Revises: 
Create Date: 2026-06-09 05:41:39.898329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60c6bc71bfa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'siswa', 'wali', ['wali_id'], ['id'])
    op.alter_column('wali', 'nama',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('wali', 'no_hp',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('wali', 'alamat',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wali', 'alamat',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('wali', 'no_hp',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('wali', 'nama',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.drop_constraint(None, 'siswa', type_='foreignkey')
    # ### end Alembic commands ###
